# Benchmark CI Configuration
# This file configures the benchmark CI system behavior

# Benchmark execution settings
benchmark:
  # Default timeout for benchmark runs (in Go duration format)
  default_timeout: "10m"
  
  # Maximum timeout for long-running benchmarks
  max_timeout: "30m"
  
  # Number of benchmark iterations (Go's -benchtime equivalent)
  iterations: "1s"
  
  # Enable memory allocation tracking
  track_memory: true
  
  # Enable CPU profiling
  cpu_profiling: true
  
  # Enable memory profiling
  memory_profiling: true
  
  # Profile output directory
  profile_dir: "profiles"

# CI workflow settings
ci:
  # Go versions to test against
  go_versions:
    - "1.20"
    - "1.21"
    - "1.22"
  
  # Operating systems to test on
  operating_systems:
    - "ubuntu-latest"
    # - "windows-latest"  # Uncomment to enable Windows testing
    # - "macos-latest"    # Uncomment to enable macOS testing
  
  # Schedule for daily benchmarks (cron format)
  schedule: "0 2 * * *"  # Daily at 2 AM UTC
  
  # Artifact retention settings
  artifacts:
    # Retention period for benchmark profiles (days)
    profiles_retention: 30
    
    # Retention period for benchmark results (days)
    results_retention: 90
    
    # Maximum artifact size (MB)
    max_size: 100

# Benchmark categories and their settings
categories:
  parser:
    enabled: true
    timeout: "5m"
    patterns:
      - "BenchmarkParse"
  
  storage:
    enabled: true
    timeout: "10m"
    patterns:
      - "BenchmarkWrite"
  
  http:
    enabled: true
    timeout: "5m"
    patterns:
      - "BenchmarkHTTP"
  
  e2e:
    enabled: true
    timeout: "15m"
    patterns:
      - "BenchmarkEndToEnd"
      - "BenchmarkConcurrent"
  
  memory:
    enabled: true
    timeout: "10m"
    patterns:
      - "BenchmarkMemory"

# Performance thresholds and alerts
performance:
  # Enable performance regression detection
  regression_detection: true
  
  # Threshold for performance regression alert (percentage)
  regression_threshold: 10.0
  
  # Threshold for performance improvement alert (percentage)
  improvement_threshold: 5.0
  
  # Minimum number of benchmark runs for statistical significance
  min_runs: 3
  
  # Confidence level for statistical tests (0.95 = 95%)
  confidence_level: 0.95

# Local development settings
local:
  # Default output directory for benchmark results
  output_dir: "benchmark-results"
  
  # Enable colored output in terminal
  colored_output: true
  
  # Auto-cleanup of temporary files
  auto_cleanup: true
  
  # Verbose logging level
  verbose: false

# Integration settings
integration:
  # Enable PR comments with benchmark results
  pr_comments: true
  
  # Enable status checks on PRs
  status_checks: true
  
  # Enable benchmark result comparison
  result_comparison: true
  
  # Comment template for PRs
  comment_template: |
    ## 🚀 Benchmark Results Summary
    
    Here are the latest benchmark results for this PR:
    
    ```
    {summary}
    ```
    
    Full results are available in the workflow artifacts.
    
    {regression_warning}

# Advanced settings
advanced:
  # Enable parallel benchmark execution
  parallel_execution: true
  
  # Maximum number of parallel jobs
  max_parallel_jobs: 4
  
  # Enable benchmark result caching
  result_caching: true
  
  # Cache TTL (time to live) in hours
  cache_ttl: 24
  
  # Enable benchmark result compression
  result_compression: true
  
  # Compression level (1-9, 9 being highest)
  compression_level: 6
