run:
  timeout: 10m
  go: "1.20"
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true

linters:
  enable:
    # Code formatting and style
    - gofmt
    - goimports
    - whitespace
    - gocognit
    - gocyclo
    - gomnd
    - goprintffuncname
    - goconst
    - dupl
    - funlen
    - lll
    - nestif
    - wsl
    
    # Code correctness
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - deadcode
    - varcheck
    - structcheck
    - typecheck
    - unparam
    - unconvert
    - unconvert
    - gosec
    - noctx
    - nolintlint
    - nakedret
    
    # Performance
    - prealloc
    - makezero
    - nilnil
    - tenv
    - usestdlibvars
    
    # Best practices
    - gocritic
    - godox
    - godot
    - goheader
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gomnd:
    checks: argument,case,condition,operation,return,assign
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentFormatting
      - hugeParam
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - gocyclo
        - dupl
    - path: test/
      linters:
        - gomnd
        - gocyclo
        - dupl
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
