name: Auto PR Creator

on:
  push:
    branches:
      - 'test*'
      - 'test'
      - 'feature*'
      - 'dev*'
  workflow_dispatch: # Allow manual triggering

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Need full history for PR creation
    
    - name: Check if PR already exists
      id: check-pr
      run: |
        # Get current branch name
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        
        # Check if PR already exists using GitHub CLI
        if gh pr list --head "$BRANCH_NAME" --base main --json number | grep -q "number"; then
          echo "pr_exists=true" >> $GITHUB_OUTPUT
          echo "PR already exists for branch $BRANCH_NAME"
        else
          echo "pr_exists=false" >> $GITHUB_OUTPUT
          echo "No PR found for branch $BRANCH_NAME"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Pull Request
      if: steps.check-pr.outputs.pr_exists == 'false'
      run: |
        # Get current branch name
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        
        # Create PR with optimized settings
        gh pr create \
          --title "Auto PR: $BRANCH_NAME → main" \
          --body "Automatically created PR from $BRANCH_NAME branch.

## Changes
- Auto-generated PR from test branch
- Created by CI/CD pipeline

## Checklist
- [ ] Code review completed
- [ ] Tests passing
- [ ] Ready for merge" \
          --base main \
          --head "$BRANCH_NAME" \
          --draft \
          --assignee "@me"
        
        echo "✅ Pull request created successfully for $BRANCH_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Skip if PR exists
      if: steps.check-pr.outputs.pr_exists == 'true'
      run: |
        echo "⏭️ PR already exists, skipping creation"
