name: Auto PR Creator

on:
  push:
    branches:
      - 'test*'
      - 'test'
      - 'feature*'
      - 'dev*'
  workflow_dispatch: # Allow manual triggering

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Need full history for PR creation
    
    - name: Install GitHub CLI
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
    
    - name: Check if PR already exists
      id: check-pr
      run: |
        # Get current branch name
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        
        # Check if PR already exists using GitHub CLI
        if gh pr list --head "$BRANCH_NAME" --base main --json number | grep -q "number"; then
          echo "pr_exists=true" >> $GITHUB_OUTPUT
          echo "PR already exists for branch $BRANCH_NAME"
        else
          echo "pr_exists=false" >> $GITHUB_OUTPUT
          echo "No PR found for branch $BRANCH_NAME"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Pull Request
      if: steps.check-pr.outputs.pr_exists == 'false'
      run: |
        # Get current branch name
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        
        # Create PR with optimized settings
        gh pr create \
          --title "Auto PR: $BRANCH_NAME → main" \
          --body "Automatically created PR from $BRANCH_NAME branch. Auto-generated by CI/CD pipeline." \
          --base main \
          --head "$BRANCH_NAME" \
          --draft \
          --assignee "@me"
        
        echo "✅ Pull request created successfully for $BRANCH_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Skip if PR exists
      if: steps.check-pr.outputs.pr_exists == 'true'
      run: |
        echo "⏭️ PR already exists, skipping creation"
