name: CI Simple

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Verify Go module
      run: |
        go mod download
        go mod verify
        
    - name: Run tests
      run: go test -v ./...
      working-directory: ${{ github.workspace }}
      
    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...
      working-directory: ${{ github.workspace }}
      
    - name: Show coverage
      run: go tool cover -func=coverage.out
      working-directory: ${{ github.workspace }}
