name: CI Simple

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        

    - name: Download dependencies
      run: go mod tidy
           
    - name: Run tests
      run: go test -v  ./...
      working-directory: .
      
    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...
      working-directory: .
      
    - name: Show coverage
      run: go tool cover -func=coverage.out
      working-directory: .
      
    - name: Quick benchmark check
      run: |
        echo "Running quick benchmark check..."
        go test -bench=. -benchmem -timeout=2m ./test/ | head -20
      working-directory: .
