name: update-readme-badges

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Download dependencies
      run: go mod tidy
           
    - name: Run tests with coverage
      run: go test -v -coverprofile=coverage.out ./...
      
    - name: Get coverage percentage
      id: coverage
      run: |
        COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
        echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT
        echo "Coverage: $COVERAGE%"
      
    - name: Get Go version
      id: go_version
      run: |
        GO_VERSION=$(go version | awk '{print $3}' | sed 's/go//')
        echo "go_version=$GO_VERSION" >> $GITHUB_OUTPUT
        echo "Go version: $GO_VERSION"
      
    - name: Update README with badges
      run: |
        # Create badges without URLs (non-clickable)
        BUILD_BADGE="![Build Status](https://img.shields.io/badge/build-passing-brightgreen?style=flat-square)"
        COVERAGE_BADGE="![Coverage](https://img.shields.io/badge/coverage-${{ steps.coverage.outputs.coverage }}%25-brightgreen?style=flat-square)"
        GO_VERSION_BADGE="![Go Version](https://img.shields.io/badge/go-${{ steps.go_version.outputs.go_version }}-blue?style=flat-square)"
        LICENSE_BADGE="![License](https://img.shields.io/badge/license-AGPL%20v3.0-red?style=flat-square)"
        
        # Update README.md - replace existing badges with new ones
        sed -i "s|!\[Build Status\].*|$BUILD_BADGE|" README.md
        sed -i "s|!\[Coverage\].*|$COVERAGE_BADGE|" README.md
        sed -i "s|!\[Go Version\].*|$GO_VERSION_BADGE|" README.md
        sed -i "s|!\[License\].*|$LICENSE_BADGE|" README.md
        
        # Add coverage badge if it doesn't exist
        if ! grep -q "!\[Coverage\]" README.md; then
          # Insert after the first line (title)
          sed -i "1a\\$COVERAGE_BADGE" README.md
        fi
        
        echo "README badges updated successfully"
      
    - name: Commit and push changes
      run: |
        # Ensure we're on the correct branch
        git checkout ${{ github.ref_name }}
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Update README badges [skip ci]"
          git push origin ${{ github.ref_name }}
        fi
